name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MSVC if under Windows
        uses: ilammy/msvc-dev-cmd@v1

      # - name: Install CMake
      #   run: |
      #     python -m pip install cmake -U

      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          boost_version: 1.83.0

      - name: Install other dependencies
        run: |
          vcpkg install
          vcpkg integrate install
          echo "VCPKG_ROOT=$VCPKG_ROOT" >> $GITHUB_ENV

      - name: DEBUG
        run: |
          echo $VCPKG_ROOT
        shell: bash

      - name: Build PicoGK Runtime
        run: |
          cmake -B build
          cmake --build build --config Release
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
